<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-EII4P66" failures="2" tests="4" name="tests.VerifyConnectionPage" time="162.052" errors="0" timestamp="2022-10-03T14:13:57 IST" skipped="0">
  <testcase classname="tests.VerifyConnectionPage" name="verifyConnectionsLink" time="29.297">
    <failure message="expected [https://www.linkedin.com/mynetwork/invite-connect/connections/] but found [https://www.linkedin.com/mynetwork/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.linkedin.com/mynetwork/invite-connect/connections/] but found [https://www.linkedin.com/mynetwork/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at tests.VerifyConnectionPage.verifyConnectionsLink(VerifyConnectionPage.java:94)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyConnectionsLink -->
  <system-out/>
  <testcase classname="tests.VerifyConnectionPage" name="verifyGroupsLink" time="23.789">
    <failure message="expected [https://www.linkedin.com/groups/] but found [https://www.linkedin.com/mynetwork/]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [https://www.linkedin.com/groups/] but found [https://www.linkedin.com/mynetwork/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at tests.VerifyConnectionPage.verifyGroupsLink(VerifyConnectionPage.java:105)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyGroupsLink -->
  <system-out/>
  <testcase classname="tests.VerifyConnectionPage" name="verifyConnectionsLink" time="56.009"/>
  <system-out/>
  <testcase classname="tests.VerifyConnectionPage" name="verifyGroupsLink" time="52.957"/>
  <system-out/>
</testsuite> <!-- tests.VerifyConnectionPage -->
