<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-EII4P66" failures="1" tests="8" name="Test" time="292.098" errors="0" timestamp="2022-09-17T12:01:34 IST">
  <testcase classname="pack1.VerifyNewsLetterPage" name="verifyNewslettersLink" time="2.519"/>
  <testcase classname="pack1.VerifyHashtagPage" name="verifyHashtagLink" time="2.194"/>
  <testcase classname="pack1.VerifyPeopleIFollowPage" name="verifyPeopleIFollowLink" time="2.229"/>
  <testcase classname="pack1.VerifyGroupsPage" name="verifyGroupsLink" time="3.412"/>
  <testcase classname="pack1.VerifyEventsPage" name="verifyEventsLink" time="2.155"/>
  <testcase classname="pack1.VerifyContactsPage" name="verifyContactsLink" time="5.181">
    <failure type="java.lang.AssertionError" message="expected [https://www.linkedin.com/mynetwork/import-contacts/saved-contacts/] but found [https://www.linkedin.com/mynetwork/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.linkedin.com/mynetwork/import-contacts/saved-contacts/] but found [https://www.linkedin.com/mynetwork/]
at pack1.VerifyContactsPage.verifyContactsLink(VerifyContactsPage.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyContactsLink -->
  <testcase classname="pack1.VerifyPagesPage" name="verifyPagesLink" time="2.132"/>
  <testcase classname="pack1.VerifyConnectionPage" name="verifyConnectionsLink" time="2.453"/>
</testsuite> <!-- Test -->
