<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-EII4P66" failures="2" tests="5" name="FirefoxTest" time="95.673" errors="0" timestamp="2022-10-03T14:13:56 IST">
  <testcase classname="tests.VerifyContactsPage" name="@BeforeMethod openMyNetworkPage" time="15.048">
    <failure type="org.openqa.selenium.NoSuchElementException" message="Unable to locate element: //span[text()=&amp;apos;My Network&amp;apos;]
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;DESKTOP-EII4P66&amp;apos;, ip: &amp;apos;192.168.137.1&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;18.0.1.1&amp;apos;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 105.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20220922151854, moz:geckodriverVersion: 0.31.0, moz:headless: false, moz:platformVersion: 10.0, moz:processID: 18356, moz:profile: C:\Users\ABC\AppData\Local\..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 501b9d40-6660-4233-979b-b780f146809e
*** Element info: {Using=xpath, value=//span[text()=&amp;apos;My Network&amp;apos;]}">
      <![CDATA[org.openqa.selenium.NoSuchElementException: Unable to locate element: //span[text()='My Network']
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-EII4P66', ip: '192.168.137.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '18.0.1.1'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 105.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20220922151854, moz:geckodriverVersion: 0.31.0, moz:headless: false, moz:platformVersion: 10.0, moz:processID: 18356, moz:profile: C:\Users\ABC\AppData\Local\..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, moz:windowless: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 501b9d40-6660-4233-979b-b780f146809e
*** Element info: {Using=xpath, value=//span[text()='My Network']}
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at jdk.proxy2/jdk.proxy2.$Proxy18.click(Unknown Source)
at pages.HomePage.openMyNetworkPage(HomePage.java:47)
at tests.VerifyContactsPage.openMyNetworkPage(VerifyContactsPage.java:85)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod openMyNetworkPage -->
  <testcase classname="tests.VerifyContactsPage" name="@AfterMethod logOutToApp" time="-1.664786609892E9">
    <skipped/>
  </testcase> <!-- @AfterMethod logOutToApp -->
  <testcase classname="tests.VerifyContactsPage" name="@AfterClass clearPOMClassObjects" time="-1.664786609906E9">
    <skipped/>
  </testcase> <!-- @AfterClass clearPOMClassObjects -->
  <testcase classname="tests.VerifyContactsPage" name="verifyContactsLink" time="5.482">
    <failure type="java.lang.AssertionError" message="expected [https://www.linkedin.com/mynetwork/import-contacts/saved-contacts/] but found [https://www.linkedin.com/mynetwork/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.linkedin.com/mynetwork/import-contacts/saved-contacts/] but found [https://www.linkedin.com/mynetwork/]
at tests.VerifyContactsPage.verifyContactsLink(VerifyContactsPage.java:95)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyContactsLink -->
  <testcase classname="tests.VerifyConnectionPage" name="verifyConnectionsLink" time="3.987">
    <failure type="java.lang.AssertionError" message="expected [https://www.linkedin.com/mynetwork/invite-connect/connections/] but found [https://www.linkedin.com/mynetwork/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.linkedin.com/mynetwork/invite-connect/connections/] but found [https://www.linkedin.com/mynetwork/]
at tests.VerifyConnectionPage.verifyConnectionsLink(VerifyConnectionPage.java:94)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyConnectionsLink -->
  <testcase classname="tests.VerifyContactsPage" name="verifyEventsLink" time="0.0">
    <skipped/>
  </testcase> <!-- verifyEventsLink -->
  <testcase classname="tests.VerifyContactsPage" name="verifyHashtagLink" time="0.0">
    <skipped/>
  </testcase> <!-- verifyHashtagLink -->
  <testcase classname="tests.VerifyConnectionPage" name="verifyGroupsLink" time="6.249"/>
</testsuite> <!-- FirefoxTest -->
